FROM alpine:3.3
MAINTAINER Chiahao Lin <chiahao.node@gmail.com>

RUN apk add --update --no-cache git curl wget tar make gcc python g++ linux-headers libgcc libstdc++ binutils-gold fuse pkgconfig fuse-dev nodejs bash
